matrix:
  include:
  # Linux
  - os: linux
    language: generic
    sudo: required
    dist: trusty
    install:
    - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
    script:
    - . ~/.swiftenv/init
    - swift build

  # Darwin
  - os: osx
    osx_image: xcode8.3
    script: swift test

  # macOS
  - os: osx
    osx_image: xcode8.3
    language: objective-c
    install: gem install xcpretty
    script: xcodebuild test -project Color.xcodeproj -scheme Color-macOS | xcpretty --color; exit ${PIPESTATUS[0]}

  # iOS
  - os: osx
    osx_image: xcode8.3
    language: objective-c
    install: gem install xcpretty
    script: xcodebuild test -project Color.xcodeproj -scheme Color-iOS | xcpretty --color; exit ${PIPESTATUS[0]}

  # tvOS
  - os: osx
    osx_image: xcode8.3
    language: objective-c
    install: gem install xcpretty
    script: xcodebuild test -project Color.xcodeproj -scheme Color-tvOS | xcpretty --color; exit ${PIPESTATUS[0]}
